{
 "title": "Capacity Management",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "p8s_logzio_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, p8s_logzio_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{p8s_logzio_name=~\"$p8s_logzio_name\", node=~\"$node\",pod=~\"$owner_name.+\"}, pod)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info{ p8s_logzio_name=~\"$p8s_logzio_name\"}, node)"
    }
   },
   {
    "name": "owner_name",
    "label": "Workload",
    "query": {
     "query": "label_values(kube_pod_owner{p8s_logzio_name=~\"$p8s_logzio_name\"}, owner_name)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=\"$cluster\", pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "All Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization By Cluster",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\", p8s_logzio_name!=\"\"}[$__rate_interval])) by (p8s_logzio_name)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Utilization By Cluster",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}) by (p8s_logzio_name) / sum(node_memory_MemTotal_bytes{}) by (p8s_logzio_name)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Unutilized Memory And CPU by Workload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "Unutilized  CPU (requested and not used)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "topk(10,sum((sum(kube_pod_container_resource_requests{ p8s_logzio_name=~\"$p8s_logzio_name\", unit=\"core\"}) by ( p8s_logzio_name, pod, container) - sum(rate(container_cpu_usage_seconds_total{ p8s_logzio_name=~\"$p8s_logzio_name\"}[10m])) by (p8s_logzio_name, pod, container)) * on(pod) group_left(owner_name)kube_pod_owner{p8s_logzio_name=~\"$p8s_logzio_name\"}) by (p8s_logzio_name, owner_name))",
     "legendFormat": "{{region}} - {{cluster}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Unutilized  Memory (requested and not used)",
   "type": "table",
   "description": "NOTE: Many of the logengines indicate clusters that have mins set that are too high for the utilization. Verify this before tuning requests",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10,sum((sum(kube_pod_container_resource_requests{ p8s_logzio_name=~\"$p8s_logzio_name\", unit=\"byte\", resource=\"memory\"}) by (p8s_logzio_name, pod, container) - sum(container_memory_working_set_bytes{p8s_logzio_name=~\"$p8s_logzio_name\"}) by (p8s_logzio_name, pod, container)) * on(pod) group_left(owner_name) kube_pod_owner{p8s_logzio_name=~\"$p8s_logzio_name\"}) by (p8s_logzio_name, owner_name))",
     "legendFormat": " {{p8s_logzio_name}} - {{owner_kind}}"
    }
   ]
  },
  { "title": "Nods Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Node CPU Utilization",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{p8s_logzio_name=~\"$p8s_logzio_name\", mode=\"idle\"}[$__rate_interval])) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Node Memory Utilization",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{p8s_logzio_name=~\"$p8s_logzio_name\"}) by (kubernetes_node) \n\n-\n\n(sum(node_memory_MemFree_bytes{p8s_logzio_name=~\"$p8s_logzio_name\"}) by (kubernetes_node) + sum(node_memory_Cached_bytes{p8s_logzio_name=~\"$p8s_logzio_name\"}) by (kubernetes_node) + sum(node_memory_Buffers_bytes{p8s_logzio_name=~\"$p8s_logzio_name\"}) by (kubernetes_node))\n)\n\n/\nsum(node_memory_MemTotal_bytes{p8s_logzio_name=~\"$p8s_logzio_name\"}) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Number Of Nodes ",
   "type": "stat",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(sum by (node)(kube_node_status_allocatable{p8s_logzio_name=~\"$p8s_logzio_name\",  resource=~\"memory\"}) )",
     "legendFormat": "{{Total Nodes}}"
    },
    {
     "expr": "count((sum by (node)(kube_pod_container_resource_limits{resource=\"memory\", p8s_logzio_name=~\"$p8s_logzio_name\"}) ) - (sum by (node)(kube_node_status_allocatable{p8s_logzio_name=~\"$p8s_logzio_name\",  resource=~\"memory\"})) > 0 )",
     "legendFormat": "{{Nodes Memory Overcommit}}"
    }
   ]
  },
  {
   "title": "Nods Overcommit Memory",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (node)(kube_pod_container_resource_limits{resource=\"memory\", p8s_logzio_name=~\"$p8s_logzio_name\"}) ) - (sum by (node)(kube_node_status_allocatable{p8s_logzio_name=~\"$p8s_logzio_name\",  resource=~\"memory\"})) > 0 ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Pods Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Pods CPU Status By Node - $node",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{ p8s_logzio_name=~\"$p8s_logzio_name\",kubernetes_io_hostname=~\"$node\",container!=\"POD\", pod!=\"\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "(sum by (pod)(kube_pod_container_resource_limits{p8s_logzio_name=~\"$p8s_logzio_name\",node=~\"$node\",resource=\"cpu\", unit=\"core\"}))"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{p8s_logzio_name=~\"$p8s_logzio_name\",kubernetes_io_hostname=~\"$node\", cpu=\"total\", container!=\"\",mode!=\"idle\",mode!=\"iowait\"}[$__rate_interval]))by (pod)/ sum(kube_pod_container_resource_requests{p8s_logzio_name=~\"$p8s_logzio_name\",node=~\"$node\",  resource=\"cpu\"}) by (pod)) * 100"
    },
    {
     "expr": "sum by (pod)(kube_pod_container_resource_requests{p8s_logzio_name=~\"$p8s_logzio_name\",node=~\"$node\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Pods Memory Status By Node - $node",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod)(kube_pod_container_resource_limits{p8s_logzio_name=~\"$p8s_logzio_name\", node=~\"$node\",resource=\"memory\"}) ",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum by (pod)(container_memory_usage_bytes{p8s_logzio_name=~\"$p8s_logzio_name\", kubernetes_io_hostname=~\"$node\", image!=\"\", pod!=\"\"})",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": " (sum by ( pod)(container_memory_usage_bytes{p8s_logzio_name=~\"$p8s_logzio_name\", kubernetes_io_hostname=~\"$node\", image!=\"\"}) / sum (kube_pod_container_resource_requests{p8s_logzio_name=~\"$p8s_logzio_name\",node=~\"$node\", resource=\"memory\"}) by (pod))* 100",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum by (kubernetes_node,pod)(kube_pod_container_resource_requests{p8s_logzio_name=~\"$p8s_logzio_name\",node=~\"$node\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Memory Summary and Recommendations By Workloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }
  },
  {
   "title": "Memory Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(container_memory_working_set_bytes{p8s_logzio_name=~\"$p8s_logzio_name\",pod=~\"$owner_name.+\",container=~\"$container\"})",
     "legendFormat": "{{pod}} - {{container}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{ p8s_logzio_name=~\"$p8s_logzio_name\", resource=\"memory\", container=~\"$container\", pod=~\"$owner_name.+\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Min/Max/Average Memory Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{p8s_logzio_name=~\"$p8s_logzio_name\",pod=~\"$owner_name.+\",container=~\"$container\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "min(container_memory_working_set_bytes{p8s_logzio_name=~\"$p8s_logzio_name\",pod=~\"$pod\",container=~\"$container\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{p8s_logzio_name=~\"$p8s_logzio_name\", resource=\"memory\", container=~\"$container\", pod=~\"$owner_name.+\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "avg(container_memory_working_set_bytes{p8s_logzio_name=~\"$p8s_logzio_name\",pod=~\"$owner_name.+\",container=~\"$container\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{ p8s_logzio_name=~\"$p8s_logzio_name\", resource=\"memory\", container=~\"$container\", pod=~\"$owner_name.+\"}) by (container)",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(max_over_time(container_memory_working_set_bytes{p8s_logzio_name=~\"$p8s_logzio_name\",pod=~\"$owner_name.+\",container=~\"$container\"}[90d])) * 1.1",
     "legendFormat": "Recommended Memory Request"
    }
   ]
  },
  {
   "title": "Current Memory Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(kube_pod_container_resource_requests{ p8s_logzio_name=~\"$p8s_logzio_name\", resource=\"memory\", container=~\"$container\", pod=~\"$owner_name.+\"})) ",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Rec. Memory Request",
   "type": "stat",
   "description": "Recommending Max memory from last 90 days + 10%",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(container_memory_working_set_bytes{p8s_logzio_name=~\"$p8s_logzio_name\",pod=~\"$owner_name.+\",container=~\"$container\"}[90d])) * 1.1",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Current Memory Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(kube_pod_container_resource_limits{p8s_logzio_name=~\"$p8s_logzio_name\", resource=\"memory\", container=~\"$container\", pod=~\"$owner_name.+\"})) by (container)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "90 Day Max Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(container_memory_working_set_bytes{p8s_logzio_name=~\"$p8s_logzio_name\",pod=~\"$owner_name.+\",container=~\"$container\"}[90d]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Memory Savings Potential",
   "type": "stat",
   "description": "This is taking what the new request should be (90 day max usage * 1.2) - the max existing usage to find a conservative estimate of the amount of GiB this could roughly save",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(max(kube_pod_container_resource_requests{p8s_logzio_name=~\"$p8s_logzio_name\", resource=\"memory\", container=~\"$container\", pod=~\"$owner_name.+\"}) by (container)) - (max(max_over_time(container_memory_working_set_bytes{p8s_logzio_name=~\"$p8s_logzio_name\",pod=~\"$owner_name.+\",container=~\"$container\"}[90d])) * 1.1)) * count(container_memory_working_set_bytes{p8s_logzio_name=~\"$p8s_logzio_name\",pod=~\"$owner_name.+\",container=~\"$container\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "CPU Summary and Recommendations By Workloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 }
  },
  {
   "title": "CPU Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{p8s_logzio_name=~\"$p8s_logzio_name\", pod=~\"$owner_name.+\", image!=\"\", container=~\"$container\"}[$__rate_interval])) by (pod, container)",
     "legendFormat": "{{pod}} - {{container}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{p8s_logzio_name=~\"$p8s_logzio_name\", resource=\"cpu\", container=~\"$container\", pod=~\"$owner_name.+\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Min/Max/Average CPU Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(sum(rate(container_cpu_usage_seconds_total{ p8s_logzio_name=~\"$p8s_logzio_name\", pod=~\"$owner_name.+\", image!=\"\", container=~\"$container\"}[$__rate_interval])) by (pod, container))",
     "legendFormat": "Min"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{p8s_logzio_name=~\"$p8s_logzio_name\", resource=\"cpu\", container=~\"$container\", pod=~\"$owner_name.+\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max(sum(rate(container_cpu_usage_seconds_total{ p8s_logzio_name=~\"$p8s_logzio_name\", pod=~\"$owner_name.+\", image!=\"\", container=~\"$container\"}[$__rate_interval])) by (pod, container))",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(sum(rate(container_cpu_usage_seconds_total{p8s_logzio_name=~\"$p8s_logzio_name\", pod=~\"$owner_name.+\", image!=\"\", container=~\"$container\"}[$__rate_interval])) by (pod, container))",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{p8s_logzio_name=~\"$p8s_logzio_name\", resource=\"cpu\", container=~\"$container\", pod=~\"$owner_name.+\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(avg_over_time(\n  sum by (container, pod) (\n    rate(container_cpu_usage_seconds_total{p8s_logzio_name=~\"$p8s_logzio_name\", pod=~\"$owner_name.+\", container=~\"$container\"}[5m])\n  )[30d:]\n)) * 1.25",
     "legendFormat": "Recommended CPU Request"
    }
   ]
  },
  {
   "title": "Current CPU Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(kube_pod_container_resource_requests{p8s_logzio_name=~\"$p8s_logzio_name\", resource=\"cpu\", container=~\"$container\", pod=~\"$owner_name.+\"}) )by (container)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Rec. CPU Request",
   "type": "stat",
   "description": "Recommending 25% above the average usage for the last 30 days.\n\nSet to a minimum of 0.1",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n  sum by (container, pod) (\n    rate(container_cpu_usage_seconds_total{p8s_logzio_name=~\"$p8s_logzio_name\", pod=~\"$owner_name.+\", container=~\"$container\"}[5m])\n  )[30d:]\n)) * 1.25"
    }
   ]
  },
  {
   "title": "Current CPU Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{ p8s_logzio_name=~\"$p8s_logzio_name\", resource=\"cpu\", container=~\"$container\", pod=~\"$owner_name.+\"}) by (container)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "30 day CPU Average",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n  sum by (container, pod) (\n    rate(container_cpu_usage_seconds_total{p8s_logzio_name=~\"$p8s_logzio_name\", pod=~\"$owner_name.+\", container=~\"$container\"}[5m])\n  )[30d:]\n))"
    }
   ]
  },
  {
   "title": "CPU Saving Potential (estimate)",
   "type": "stat",
   "description": "This is taking the request - recommended request * number of containers.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{p8s_logzio_name=~\"$p8s_logzio_name\", resource=\"cpu\", container=~\"$container\", pod=~\"$owner_name.+\"})"
    },
    {
     "expr": "avg(avg_over_time(\n  sum by (container, pod) (\n    rate(container_cpu_usage_seconds_total{p8s_logzio_name=~\"$p8s_logzio_name\", pod=~\"$owner_name.+\", container=~\"$container\"}[5m])\n  )[30d:]\n)) * 1.25"
    },
    {
     "expr": "count(kube_pod_container_resource_requests{ p8s_logzio_name=~\"$p8s_logzio_name\", resource=\"cpu\", container=~\"$container\", pod=~\"$owner_name.+\"})"
    },
    { "expression": "($C - $A) * $D", "type": "math" }
   ]
  },
  { "title": "Containers Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Container Resource By Cluster",
   "type": "table",
   "description": "This table will make the assumption that the requests for the containers are consistent across workloads, which may not always be the case. Use it as a guide, not fact.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{p8s_logzio_name=~\"$p8s_logzio_name\"}[$__rate_interval])) by (container)"
    },
    {
     "expr": "max(container_memory_working_set_bytes{p8s_logzio_name=~\"$p8s_logzio_name\"}) by (container)"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{p8s_logzio_name=~\"$p8s_logzio_name\", unit=\"core\"}) by (container)"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{p8s_logzio_name=~\"$p8s_logzio_name\", unit=\"byte\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{p8s_logzio_name=~\"$p8s_logzio_name\", unit=\"core\"}) by ( container) - sum(rate(container_cpu_usage_seconds_total{p8s_logzio_name=~\"$p8s_logzio_name\"}[$__rate_interval])) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{p8s_logzio_name=~\"$p8s_logzio_name\", unit=\"byte\"}) by (container) - (sum(container_memory_working_set_bytes{p8s_logzio_name=~\"$p8s_logzio_name\"}) by (container))"
    },
    {
     "expr": "count(kube_pod_container_info{p8s_logzio_name=~\"$p8s_logzio_name\"}) by ( container)"
    },
    {
     "expr": "count(kube_pod_container_info{container=~\"$container\"}) by (p8s_logzio_name)"
    }
   ]
  }
 ]
}